=== vainia/Learning-XML/03_21_2017/03_21_2017.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:group name="adresGroup">
			<xsd:sequence>

		<xsd:element name="ulica" type="xsd:string" />
		<xsd:element name="dom" type="xsd:integer"/>
		<xsd:element name="lokal" type="xsd:integer"/>
		<xsd:element name="miasto" type="xsd:string"/>

		<xsd:element name="kod">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:pattern value="[0-9]{2}-[0-9]{3}"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:element>

			</xsd:sequence>
	</xsd:group>

	<xsd:group name="kontaktGroup">
			<xsd:sequence>

			<xsd:element name="nazwa_" type="xsd:string" />
			<xsd:element name="ulica_" type="xsd:string" />
			<xsd:element name="dom_" type="xsd:integer"/>
			<xsd:element name="lokal_" type="xsd:integer"/>
			<xsd:element name="miasto_" type="xsd:string"/>

			<xsd:element name="kod_">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:pattern value="[0-9]{2}-[0-9]{3}"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>

			<xsd:element name="tel_" type="xsd:integer"/>
			<xsd:element name="fax_" type="xsd:integer"/>
			<xsd:element name="data_otwarcia_" type="xsd:time"/>

			</xsd:sequence>
	</xsd:group>

	<xsd:element name="lista">
		<xsd:complexType>
			<xsd:sequence>

				<xsd:element name="dany_osobowy">
					<xsd:complexType>
						<xsd:sequence>

							<xsd:element name="imie" maxOccurs="4">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="nr" type="xsd:string" />
											<xsd:attribute name="type" type="xsd:string" />
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>

							<xsd:element name="nazwisko" type="xsd:string" />
							<xsd:element name="data_ur" type="xsd:date"/>
							<xsd:element name="m_urodzenia" type="xsd:string"/>

							<xsd:element name="nip">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:pattern value="[0-9]{3}-[0-9]{3}-[0-9]{4}"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>

								<xsd:element name="pesel">
									<xsd:simpleType>
										<xsd:restriction base="xsd:string">
											<xsd:pattern value="\d{11}"/>
										</xsd:restriction>
									</xsd:simpleType>
								</xsd:element>

								<xsd:element name="plec">
									<xsd:simpleType>
										<xsd:restriction base="xsd:integer">
											<xsd:minInclusive value="1"/>
											<xsd:maxInclusive value="2"/>
										</xsd:restriction>
									</xsd:simpleType>
								</xsd:element>

								<xsd:element name="stan" type="xsd:string"/>

								<xsd:element name="nr_wpisu">
									<xsd:simpleType>
										<xsd:restriction base="xsd:string">
											<xsd:pattern value="[0-9]{2}-[0-9]{5}"/>
										</xsd:restriction>
									</xsd:simpleType>
								</xsd:element>

							</xsd:sequence>
						</xsd:complexType>
					</xsd:element>

				<xsd:element name="adres">
					<xsd:complexType>
						<xsd:sequence>

							<xsd:element name="zameldowania">
								<xsd:complexType>
									<xsd:sequence>

										<xsd:group ref="adresGroup"/>
										<xsd:element name="panstwo" type="xsd:string"/>

									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>

							<xsd:element name="zamieszkania">
								<xsd:complexType>
									<xsd:sequence>

										<xsd:group ref="adresGroup"/>

									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>

							<xsd:element name="korespondercyjny">
								<xsd:complexType>
									<xsd:sequence>

										<xsd:group ref="adresGroup"/>

									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>

						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>

				<xsd:element name="kontakt">
					<xsd:complexType>
						<xsd:sequence>

							<xsd:element name="tel" maxOccurs="3">
								<xsd:complexType>
									<xsd:simpleContent>

										<xsd:extension base="xsd:string">
											<xsd:attribute name="nr" type="xsd:string" />
											<xsd:attribute name="type" type="xsd:string" />
										</xsd:extension>

									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>

							<xsd:element name="mail" type="xsd:string" />

						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>

				<xsd:element name="wyksztalcenie">
					<xsd:complexType>
						<xsd:sequence>

							<xsd:element name="tytul" type="xsd:integer" />

							<xsd:element name="ukonczone_uczelnie">
								<xsd:complexType>
									<xsd:simpleContent>

										<xsd:extension base="xsd:string">
											<xsd:attribute name="nr" type="xsd:string" />
										</xsd:extension>

									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>

						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>

				<xsd:element name="jezyki_obce">
					<xsd:complexType>
						<xsd:sequence>

							<xsd:element name="jezyk">
								<xsd:complexType>
									<xsd:simpleContent>

										<xsd:extension base="xsd:string">
											<xsd:attribute name="nr" type="xsd:integer" />
											<xsd:attribute name="stopien" type="xsd:integer" />
										</xsd:extension>

									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>

						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>

				<xsd:element name="rodzaj_ukonczenej_aplikacji" type="xsd:integer" />
				<xsd:element name="aktywnosc_zawodowa" type="xsd:integer" />
				<xsd:element name="forma_wykonania_zawodu" type="xsd:integer" />

				<xsd:element name="specjalizacja">
					<xsd:complexType>
						<xsd:simpleContent>

							<xsd:extension base="xsd:string">
								<xsd:attribute name="nr" type="xsd:integer" />
							</xsd:extension>

						</xsd:simpleContent>
					</xsd:complexType>
				</xsd:element>

				<xsd:element name="kontakt_do_osoby">
					<xsd:complexType>
						<xsd:sequence>

							<xsd:element name="kancelaria">
								<xsd:complexType>
									<xsd:sequence>

										<xsd:group ref="kontaktGroup"/>

									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>

							<xsd:element name="filia">
								<xsd:complexType>
									<xsd:sequence>

										<xsd:group ref="kontaktGroup"/>

										<xsd:element name="data_wpisu_">
											<xsd:complexType>
												<xsd:sequence>

													<xsd:element name="rok_" type="xsd:integer" />
													<xsd:element name="miesiac_" type="xsd:integer" />
													<xsd:element name="dzien_" type="xsd:integer" />

												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>

										<xsd:element name="numer_rejestru_" type="xsd:integer" />
										<xsd:element name="stan_" type="xsd:integer" />

									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>

							<xsd:element name="mejsce_pracy">
								<xsd:complexType>
									<xsd:sequence>

										<xsd:group ref="kontaktGroup"/>

									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>

						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>

			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== vainia/Learning-XML/03_21_2017/03_21_2017.xml
<?xml version="1.0" encoding="ISO-8859-2"?>

<lista xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="03_21_2017.xsd">
	<dany_osobowy>
		<imie nr="1">Ivan</imie>
		<imie nr="2">Jan</imie>
		<imie type="matki">Tetiana</imie>
		<imie type="ojca">Gennadii</imie>
		<nazwisko>Zhezhel</nazwisko>
		<data_ur>1998-05-28</data_ur>
		<m_urodzenia>Warszawa</m_urodzenia>
		<nip>321-123-3214</nip>
		<pesel>12345678910</pesel>
		<plec>2</plec>
		<stan>MÅ‚odzieniec</stan>
		<nr_wpisu>12-23189</nr_wpisu>
	</dany_osobowy>
	<adres>
		<zameldowania>
			<ulica>Pierwsza</ulica>
			<dom>12</dom>
			<lokal>13</lokal>
			<miasto>Warszawa</miasto>
			<kod>03-477</kod>
			<panstwo>Polskie</panstwo>
		</zameldowania>
		<zamieszkania>
			<ulica>Heronima</ulica>
			<dom>1</dom>
			<lokal>22</lokal>
			<miasto></miasto>
			<kod>03-554</kod>
		</zamieszkania>
		<korespondercyjny>
			<ulica>Druga</ulica>
			<dom>11</dom>
			<lokal>15</lokal>
			<miasto>Lublin</miasto>
			<kod>03-421</kod>
		</korespondercyjny>
	</adres>
	<kontakt>
		<tel type="1" nr="1">512000412</tel>
		<tel type="1" nr="2">512000112</tel>
		<tel type="2" nr="1">331241244</tel>
		<mail>example@example.com</mail>
 </kontakt>
	<wyksztalcenie>
		<tytul>1</tytul>
		<ukonczone_uczelnie nr="1"></ukonczone_uczelnie>
	</wyksztalcenie>
	<jezyki_obce>
		<jezyk nr="1" stopien="2">Angielski</jezyk>
	</jezyki_obce>
	<rodzaj_ukonczenej_aplikacji>4</rodzaj_ukonczenej_aplikacji>
	<aktywnosc_zawodowa>7</aktywnosc_zawodowa>
	<forma_wykonania_zawodu>5</forma_wykonania_zawodu>
	<specjalizacja nr="1">I don't know</specjalizacja>
	<kontakt_do_osoby>
		<kancelaria>
			<nazwa_>Text</nazwa_>
			<ulica_>Text</ulica_>
			<dom_>11</dom_>
			<lokal_>15</lokal_>
			<miasto_>Lublin</miasto_>
			<kod_>03-421</kod_>
			<tel_>12345543</tel_>
			<fax_>65432345</fax_>
			<data_otwarcia_>12:43:21</data_otwarcia_>
		</kancelaria>
		<filia>
			<nazwa_>Text</nazwa_>
			<ulica_>Text</ulica_>
			<dom_>11</dom_>
			<lokal_>15</lokal_>
			<miasto_>Lublin</miasto_>
			<kod_>03-421</kod_>
			<tel_>12345543</tel_>
			<fax_>65432345</fax_>
			<data_otwarcia_>12:43:21</data_otwarcia_>
			<data_wpisu_>
				<rok_>1813</rok_>
				<miesiac_>11</miesiac_>
				<dzien_>24</dzien_>
			</data_wpisu_>
			<numer_rejestru_>25364743</numer_rejestru_>
			<stan_>2</stan_>
		</filia>
		<mejsce_pracy>
			<nazwa_>Text</nazwa_>
			<ulica_>Text</ulica_>
			<dom_>11</dom_>
			<lokal_>15</lokal_>
			<miasto_>Lublin</miasto_>
			<kod_>03-421</kod_>
			<tel_>12345543</tel_>
			<fax_>65432345</fax_>
			<data_otwarcia_>12:43:21</data_otwarcia_>
		</mejsce_pracy>
	</kontakt_do_osoby>
</lista>
